### ISSUE TITLE
Problems compiling with xcode 12 and Charts 3.6.0/4.0.0

### ISSUE THREAD

**Issue by poml88** [thierryH91200/DemoChartOSX-4#1]
Hi,
I am trying to compile your Demo (thanks for that). But I get tons of issues.
What version of xcode are you using and what version of Charts?
I am happy to give more details.
I am able to compile the real time example that you supplied in the Charts repository.
Thanks
Philipp

**Comment by thierryH91200** [comment]
<img width="2672" alt="Capture d’écran 2021-01-25 à 19 04 48" src="https://user-images.githubusercontent.com/6251463/105746884-4c71bc80-5f40-11eb-938f-cf9b5b60edff.png">
Chart version 4.0.0 and Xcode Version 12.3 (12C33)
i come to run a last commit just a moment
retry please
"download the zip again

**Comment by thierryH91200** [comment]
<img width="1946" alt="Capture d’écran 2021-01-25 à 19 11 13" src="https://user-images.githubusercontent.com/6251463/105747545-2ef12280-5f41-11eb-929b-171c4dbf0e2e.png">

**Comment by poml88** [comment]
Thanks it is building now. I am not sure why. I cloned the repository again as you suggested and also cleaned the build directory.

**Comment by poml88** [comment]
Got
`2021-01-25 19:42:44.989871+0100 DemoChartOSX V4[3442:133208] Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file Charts/PieRadarChartViewBase.swift, line 443`
though...

**Comment by poml88** [comment]
My real time chart looks a bit funny though... :-))

![grafik](https://user-images.githubusercontent.com/68424827/105751413-4252bc80-5f46-11eb-847d-f6c5182f3a13.png)

**Comment by thierryH91200** [comment]
clic on the bar right cubic filled and what you want

**Comment by poml88** [comment]
Got it! It was on filled + stepped.

**Comment by thierryH91200** [comment]
i come to run a last commit just a moment retry please "download the zip again
bugs on  HalfPieChart when you decrease or increase the window. I can't do anything

**Comment by poml88** [comment]
Still the same:
2021-01-25 20:54:03.933561+0100 DemoChartOSX V4[4182:157461] Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file Charts/PieRadarChartViewBase.swift, line 443
But I am not doing anything. I click on "Pie Chart" on the left and then it starts spinning and stops after a few seconds.

Thanks for the realtime chart. Now I have to figure out how to do my ECG. My data is in arrays, the graph is in another viewcontroller and I would prefer the date to move from left to right and at the right end start from the left again...
You don't happen to have an example? Just joking... ;-)
